# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authentication.ui',
# licensing of 'authentication.ui' applies.
#
# Created: Fri Jul 26 16:04:39 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("background-image: url(C:/Users/Prabal Shetty/PycharmProjects/InternshipP1/LoginBg.jpg);")

        self.usernamelabel = QtWidgets.QLabel(self.frame)
        self.usernamelabel.setGeometry(QtCore.QRect(180, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.usernamelabel.setScaledContents(False)
        self.usernamelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usernamelabel.setObjectName("usernamelabel")
        self.passwordlabel = QtWidgets.QLabel(self.frame)
        self.passwordlabel.setGeometry(QtCore.QRect(180, 240, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.passwordlabel.setFont(font)
        self.passwordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordlabel.setObjectName("passwordlabel")
        self.username_lineedit = QtWidgets.QLineEdit(self.frame)
        self.username_lineedit.setGeometry(QtCore.QRect(320, 220, 231, 22))
        self.username_lineedit.setObjectName("username_lineedit")
        self.password_lineedit = QtWidgets.QLineEdit(self.frame)
        self.password_lineedit.setGeometry(QtCore.QRect(320, 250, 231, 22))
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        #self.googlesignin = QtWidgets.QLabel(self.frame)
        #self.googlesignin.setGeometry(QtCore.QRect(160, 360, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        #self.googlesignin.setFont(font)
        #self.googlesignin.setScaledContents(False)
        #self.googlesignin.setAlignment(QtCore.Qt.AlignCenter)
        #self.googlesignin.setObjectName("googlesignin")
        self.googleloginbutton = QtWidgets.QPushButton(self.frame)
        self.googleloginbutton.setGeometry(QtCore.QRect(370, 360, 201, 41))
        self.googleloginbutton.setText("")
        self.googleloginbutton.setObjectName("googleloginbutton")

        self.googleloginbutton.setStyleSheet("background-image: url(C:/Users/Prabal Shetty/PycharmProjects/InternshipP1/GoogleSignIn.png);")
        self.loginbutton = QtWidgets.QPushButton(self.frame)
        self.loginbutton.setEnabled(True)
        self.loginbutton.setGeometry(QtCore.QRect(370, 280, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.loginbutton.setFont(font)
        self.loginbutton.setAutoFillBackground(True)
        self.loginbutton.setObjectName("loginbutton")
        self.loginbutton.setStyleSheet("background-image: url(C:/Users/Prabal Shetty/PycharmProjects/InternshipP1/LoginButton.png);")


        self.signin_note = QtWidgets.QLabel(self.frame)
        self.signin_note.setEnabled(True)
        self.signin_note.setGeometry(QtCore.QRect(170, 160, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.signin_note.setFont(font)
        self.signin_note.setScaledContents(False)
        self.signin_note.setAlignment(QtCore.Qt.AlignCenter)
        self.signin_note.setObjectName("signin_note")
        self.signin_note_2 = QtWidgets.QLabel(self.frame)
        self.signin_note_2.setGeometry(QtCore.QRect(170, 70, 421, 91))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(36)
        font.setWeight(50)
        font.setUnderline(True)
        font.setBold(False)
        self.signin_note_2.setFont(font)
        self.signin_note_2.setScaledContents(False)
        self.signin_note_2.setAlignment(QtCore.Qt.AlignCenter)
        self.signin_note_2.setObjectName("signin_note_2")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "DsKDirectRy", None, -1))
        self.usernamelabel.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Username :</span></p></body></html>",None, -1))
        self.passwordlabel.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Password :</span></p></body></html>", None, -1))
        self.username_lineedit.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Type in your username here", None, -1))
        self.password_lineedit.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Type in your password here", None, -1))
        #self.googlesignin.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Sign in with Google</span></p></body></html>", None, -1))
        self.loginbutton.setText(QtWidgets.QApplication.translate("MainWindow", "", None, -1))
        self.signin_note.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Enter a valid username and password</span></p></body></html>", None, -1))
        self.signin_note_2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">DsK DIRECT-RY</span></p></body></html>", None, -1))

